### ISSUE TITLE
Exercise 2: Check All or None

### ISSUE THREAD

**Issue by oubaka** [oubaka/javascript_tutorial#2]
https://github.com/oubaka/javascript_tutorial/tree/master/exercise2

Create a list of checkbox (red, green, yellow, white, black). Now create two links "Check all" and 'None'. When you click on Check All link, all checkboxes will be selected, and when you click on none link all checkboxes will be deselected (working example is gmail).

**Comment by segunadeleye** [comment]
We can have one method handle both checked state.

**Comment by oubaka** [comment]
Updated the check method as adviced

**Comment by segunadeleye** [comment]
An optimisation technique is to always save a reference to the DOM in a variable so that you would only hit the DOM once. When you are accessing the `document` more than once, especially within a function scope, it is a good practice to save the reference to `document` in a variable. Therefore;
```
Controller.prototype.getViewTemplate = function getViewTemplate(name) {
  var li = document.createElement('li');
  var checkbox = document.createElement('input');
  ...
  var label = document.createElement('label');
  ...
}
```
can be;
```
Controller.prototype.getViewTemplate = function getViewTemplate(name) {
  var doc = document;
  var li = doc.createElement('li');
  var checkbox = doc.createElement('input');
  ...
  var label = doc.createElement('label');
  ...
}
```

- https://github.com/oubaka/javascript_tutorial/blob/master/exercise4/controller.js#L49
`Event.initEvent()` is a deprecated method (https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent). Use `addEventListener()` instead.

- https://github.com/oubaka/javascript_tutorial/blob/master/exercise4/controller.js#L95
Always try as much as possible to hit the DOM as few times as possible. A good approach here is to add each `template` to a `documentFragment` after which you drop all the `template`s in the DOM once.

- https://github.com/oubaka/javascript_tutorial/blob/master/exercise4/controller.js#L98
How about `createContainerTemplate` instead of `getContainerTemplate`

- https://github.com/oubaka/javascript_tutorial/blob/master/exercise4/controller.js#L74 and https://github.com/oubaka/javascript_tutorial/blob/master/exercise4/controller.js#L75
Why are you accessing the arguments this way? Is this not redundant?

**Comment by segunadeleye** [comment]
Much better this way.
