### ISSUE TITLE
Exercise 4: Parent Checkbox and Their Children Checkbox - Movies, Drinks and Bikes

### ISSUE THREAD

**Issue by oubaka** [oubaka/javascript_tutorial#4]
https://github.com/oubaka/javascript_tutorial/tree/master/exercise4

Create a div with height 100 and scroll bars. Display a list of checkbox color, drinks, movies and bikes in this div. Now when you click on color checkbox it should display four checkboxes (red, yellow, green, blue) as a child list and color checkbox should be checked with its child list of checkboxes. Again when you click on color checkbox, child list should be hidden and its child checkboxes should get deselected (clear state). Same with movies, drink and bikes.
Movies: [Dar, Sir]
Drinks: [Coke, Pepsi, Dew]
Bikes: [V-rod, Pulsar, CBZ]

Remember: When you click on a parent checkbox and if child list checkboxes are out of visible area the div's scrollbars should scroll and child list should be visible automatically. We should not scroll the div to see them (child list of checkboxes).

**Comment by segunadeleye** [comment]
- An optimisation technique is to always save a reference to the DOM in a variable so that you would only hit the DOM once. When you are accessing the `document` more than once, especially within a function scope, it is a good practice to save the reference to `document` in a variable. Therefore;

```
Controller.prototype.getViewTemplate = function getViewTemplate(name) {
  var li = document.createElement('li');
  var checkbox = document.createElement('input');
  ...
  var label = document.createElement('label');
  ...
}
```

can be;

```
Controller.prototype.getViewTemplate = function getViewTemplate(name) {
  var doc = document;
  var li = doc.createElement('li');
  var checkbox = doc.createElement('input');
  ...
  var label = doc.createElement('label');
  ...
}
```
- https://github.com/oubaka/javascript_tutorial/blob/master/exercise4/controller.js#L49
  `Event.initEvent()` is a deprecated method (https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent). Use `addEventListener()` instead.
- https://github.com/oubaka/javascript_tutorial/blob/master/exercise4/controller.js#L95
  Always try as much as possible to hit the DOM as few times as possible. A good approach here is to add each `template` to a `documentFragment` after which you drop all the `template`s in the DOM once.
- https://github.com/oubaka/javascript_tutorial/blob/master/exercise4/controller.js#L98
  How about `createContainerTemplate` instead of `getContainerTemplate`
- https://github.com/oubaka/javascript_tutorial/blob/master/exercise4/controller.js#L74 and https://github.com/oubaka/javascript_tutorial/blob/master/exercise4/controller.js#L75
  Why are you accessing the arguments this way? Is this not redundant?

**Comment by oubaka** [comment]
made corrections as adviced

**Comment by segunadeleye** [comment]
Looks good now :100:
However, we can create the Event objects once, and afterwards dispatch when the checkboxes are checked or unchecked.
